name: Astro CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # match your local Node.js version
          cache: 'pnpm' # enable caching for pnpm dependencies

      # 3. Install pnpm via Corepack (reliable on GitHub Actions)
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 5. Build Astro project
      - name: Build project
        run: pnpm run build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Deploy to production for main branch, staging for dev branch
          publish_branch: ${{ github.ref == 'refs/heads/main' && 'gh-pages' || 'gh-pages-staging' }}
